functionsDirectory = "C:\\Users\\snoep_a5dedf8\\Desktop\\SHANNACHRISTINE\\snoep\\Shanna Noe\\Desktop\\dev\\horoscope-app\\vite-project\\netlify\\functions"
functionsDirectoryOrigin = "ui"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\snoep_a5dedf8\\Desktop\\SHANNACHRISTINE\\snoep\\Shanna Noe\\Desktop\\dev\\horoscope-app\\vite-project\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\snoep_a5dedf8\\Desktop\\SHANNACHRISTINE\\snoep\\Shanna Noe\\Desktop\\dev\\horoscope-app\\vite-project"
command = "npm run build"
functions = "C:\\Users\\snoep_a5dedf8\\Desktop\\SHANNACHRISTINE\\snoep\\Shanna Noe\\Desktop\\dev\\horoscope-app\\vite-project\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]