export const planetInSign = {
  Sun: {
    Aries: "Your core identity is bold, pioneering, and action-oriented. You lead with courage and thrive on new beginnings.",
    Taurus: "Your core identity is grounded, patient, and sensual. You value stability, comfort, and the finer things in life.",
    Gemini: "Your core identity is curious, adaptable, and communicative. You thrive on mental stimulation and variety.",
    Cancer: "Your core identity is nurturing, intuitive, and emotionally deep. Home and family are central to who you are.",
    Leo: "Your core identity is creative, warm, and confident. You naturally command attention and radiate generosity.",
    Virgo: "Your core identity is analytical, detail-oriented, and service-minded. You seek perfection and practical solutions.",
    Libra: "Your core identity is diplomatic, harmonious, and relationship-focused. You seek balance and beauty in all things.",
    Scorpio: "Your core identity is intense, transformative, and deeply perceptive. You navigate life with emotional power.",
    Sagittarius: "Your core identity is adventurous, philosophical, and freedom-loving. You seek truth and new horizons.",
    Capricorn: "Your core identity is ambitious, disciplined, and responsible. You build lasting structures through perseverance.",
    Aquarius: "Your core identity is innovative, humanitarian, and independent. You think ahead of your time and value originality.",
    Pisces: "Your core identity is compassionate, intuitive, and imaginative. You connect deeply with the spiritual and creative realms.",
  },
  Moon: {
    Aries: "Emotionally you're impulsive and passionate. You need independence and direct expression of feelings.",
    Taurus: "Emotionally you're steady and comfort-seeking. You need security, routine, and sensory pleasures to feel safe.",
    Gemini: "Emotionally you're restless and intellectually driven. You process feelings through talking and thinking.",
    Cancer: "Emotionally you're deeply sensitive and nurturing. You need a secure home base and close emotional bonds.",
    Leo: "Emotionally you're warm, dramatic, and generous. You need recognition, affection, and creative expression.",
    Virgo: "Emotionally you're practical and service-oriented. You process feelings through analysis and helping others.",
    Libra: "Emotionally you're harmony-seeking and relationship-oriented. You need peace, beauty, and partnership.",
    Scorpio: "Emotionally you're intense and deeply feeling. You need emotional depth, privacy, and transformative experiences.",
    Sagittarius: "Emotionally you're optimistic and freedom-loving. You need adventure, learning, and space to explore.",
    Capricorn: "Emotionally you're reserved and self-controlled. You need structure, achievement, and respect to feel secure.",
    Aquarius: "Emotionally you're detached and unconventional. You need intellectual stimulation and space for individuality.",
    Pisces: "Emotionally you're empathetic and dreamy. You need creative outlets, spiritual connection, and emotional flow.",
  },
  Mercury: {
    Aries: "You think and communicate quickly and directly. Your mind is competitive and pioneering in its approach.",
    Taurus: "You think methodically and practically. Your communication style is deliberate, grounded, and reliable.",
    Gemini: "Your mind is quick, versatile, and curious. You're a natural communicator who excels at multitasking ideas.",
    Cancer: "You think with your feelings and have an excellent memory. Communication is intuitive and emotionally colored.",
    Leo: "You think creatively and express yourself dramatically. Your communication style is confident and entertaining.",
    Virgo: "Your mind is precise, analytical, and detail-focused. You communicate with clarity and practical intelligence.",
    Libra: "You think diplomatically and see all sides. Your communication style is balanced, fair, and charming.",
    Scorpio: "Your mind is penetrating and investigative. You communicate with intensity and see beneath the surface.",
    Sagittarius: "You think broadly and philosophically. Your communication is enthusiastic, honest, and big-picture oriented.",
    Capricorn: "Your mind is structured and strategic. You communicate with authority, practicality, and careful planning.",
    Aquarius: "Your mind is innovative and unconventional. You think in original ways and communicate progressive ideas.",
    Pisces: "Your mind is imaginative and intuitive. You communicate through imagery, metaphor, and emotional resonance.",
  },
  Venus: {
    Aries: "In love you're passionate, direct, and chase what you want. You value excitement and bold romantic gestures.",
    Taurus: "In love you're devoted, sensual, and steadfast. You value loyalty, comfort, and physical affection.",
    Gemini: "In love you're playful, witty, and need mental connection. You value stimulating conversation and variety.",
    Cancer: "In love you're nurturing, protective, and deeply loyal. You value emotional security and domestic harmony.",
    Leo: "In love you're romantic, generous, and dramatic. You value grand gestures, loyalty, and being adored.",
    Virgo: "In love you're devoted through acts of service. You value thoughtfulness, reliability, and practical care.",
    Libra: "In love you're charming, romantic, and partnership-oriented. You value harmony, beauty, and fairness.",
    Scorpio: "In love you're intense, passionate, and all-or-nothing. You value deep emotional and physical connection.",
    Sagittarius: "In love you're adventurous, generous, and freedom-loving. You value honesty, humor, and shared exploration.",
    Capricorn: "In love you're committed, traditional, and ambitious. You value loyalty, status, and long-term partnership.",
    Aquarius: "In love you're unconventional, friendly, and independent. You value intellectual connection and personal freedom.",
    Pisces: "In love you're romantic, selfless, and deeply compassionate. You value spiritual connection and emotional depth.",
  },
  Mars: {
    Aries: "You assert yourself with directness and courage. Your energy is competitive, fast, and pioneering.",
    Taurus: "You assert yourself with patience and determination. Your energy is steady, persistent, and enduring.",
    Gemini: "You assert yourself through words and wit. Your energy is versatile, quick, and mentally driven.",
    Cancer: "You assert yourself protectively and emotionally. Your energy is defensive, nurturing, and tenacious.",
    Leo: "You assert yourself with confidence and flair. Your energy is dramatic, creative, and leadership-oriented.",
    Virgo: "You assert yourself through precision and service. Your energy is methodical, efficient, and detail-focused.",
    Libra: "You assert yourself diplomatically and through partnership. Your energy seeks balance and fairness.",
    Scorpio: "You assert yourself with intensity and strategic power. Your energy is transformative and deeply focused.",
    Sagittarius: "You assert yourself with enthusiasm and idealism. Your energy is adventurous, bold, and expansive.",
    Capricorn: "You assert yourself with discipline and ambition. Your energy is controlled, strategic, and goal-oriented.",
    Aquarius: "You assert yourself through rebellion and innovation. Your energy is unconventional and socially conscious.",
    Pisces: "You assert yourself subtly and compassionately. Your energy is spiritual, creative, and fluid.",
  },
  Jupiter: {
    Aries: "You grow through bold action and leadership. Luck comes when you take initiative and blaze new trails.",
    Taurus: "You grow through building material security. Luck comes through patience, investments, and enjoying abundance.",
    Gemini: "You grow through learning and communication. Luck comes through networking, writing, and intellectual pursuits.",
    Cancer: "You grow through nurturing and emotional wisdom. Luck comes through family, home, and caring for others.",
    Leo: "You grow through creative self-expression. Luck comes through generosity, performing, and following your heart.",
    Virgo: "You grow through service and self-improvement. Luck comes through health, detailed work, and helping others.",
    Libra: "You grow through relationships and diplomacy. Luck comes through partnerships, art, and promoting justice.",
    Scorpio: "You grow through transformation and deep research. Luck comes through investigation and shared resources.",
    Sagittarius: "You grow through philosophy and exploration. Luck comes through travel, higher education, and truth-seeking.",
    Capricorn: "You grow through discipline and responsibility. Luck comes through hard work, structure, and perseverance.",
    Aquarius: "You grow through innovation and humanitarianism. Luck comes through technology, groups, and progressive ideas.",
    Pisces: "You grow through compassion and spiritual connection. Luck comes through faith, creativity, and selfless giving.",
  },
  Saturn: {
    Aries: "Your life lessons involve learning patience and healthy self-assertion. Discipline comes through independent action.",
    Taurus: "Your life lessons involve building real security. Discipline comes through managing resources and self-worth.",
    Gemini: "Your life lessons involve focused communication. Discipline comes through structured thinking and learning.",
    Cancer: "Your life lessons involve emotional boundaries. Discipline comes through balancing nurturing with self-protection.",
    Leo: "Your life lessons involve authentic self-expression. Discipline comes through humble creativity and leadership.",
    Virgo: "Your life lessons involve practical service. Discipline comes through health routines and detailed work.",
    Libra: "Your life lessons involve committed relationships. Discipline comes through fairness, commitment, and balance.",
    Scorpio: "Your life lessons involve emotional power. Discipline comes through transformation and releasing control.",
    Sagittarius: "Your life lessons involve practical wisdom. Discipline comes through grounded philosophy and focused learning.",
    Capricorn: "Your life lessons involve mastering responsibility. Discipline comes naturally through ambition and structure.",
    Aquarius: "Your life lessons involve structured innovation. Discipline comes through balancing individuality with community.",
    Pisces: "Your life lessons involve spiritual boundaries. Discipline comes through grounding your compassion and intuition.",
  },
  Uranus: {
    Aries: "Your generation brings radical new approaches to identity and independence. You innovate through bold individuality.",
    Taurus: "Your generation revolutionizes values, finances, and sustainability. You innovate through practical transformation.",
    Gemini: "Your generation transforms communication and information. You innovate through new ways of connecting and learning.",
    Cancer: "Your generation revolutionizes home and family structures. You innovate through emotional intelligence and care.",
    Leo: "Your generation transforms creative expression and leadership. You innovate through bold artistic vision.",
    Virgo: "Your generation revolutionizes health, work, and daily life. You innovate through technology and efficiency.",
    Libra: "Your generation transforms relationships and social justice. You innovate through new partnership models.",
    Scorpio: "Your generation revolutionizes power dynamics and psychology. You innovate through deep transformation.",
    Sagittarius: "Your generation transforms beliefs and global connection. You innovate through philosophy and exploration.",
    Capricorn: "Your generation revolutionizes institutions and governance. You innovate through restructuring authority.",
    Aquarius: "Your generation transforms technology and social networks. You innovate through humanitarian progress.",
    Pisces: "Your generation revolutionizes spirituality and compassion. You innovate through imagination and empathy.",
  },
  Neptune: {
    Aries: "Your generation dreams of individual heroism and new beginnings. Collective ideals focus on pioneering courage.",
    Taurus: "Your generation dreams of sustainable beauty and security. Collective ideals focus on earthly harmony.",
    Gemini: "Your generation dreams of connected minds and fluid communication. Collective ideals focus on shared knowledge.",
    Cancer: "Your generation dreams of universal nurturing and emotional healing. Collective ideals focus on family and belonging.",
    Leo: "Your generation dreams of creative transcendence and joyful expression. Collective ideals focus on heart-centered living.",
    Virgo: "Your generation dreams of healing service and practical spirituality. Collective ideals focus on holistic well-being.",
    Libra: "Your generation dreams of ideal love and perfect harmony. Collective ideals focus on peace and artistic beauty.",
    Scorpio: "Your generation dreams of profound transformation and hidden truths. Collective ideals focus on deep healing.",
    Sagittarius: "Your generation dreams of spiritual adventure and universal truth. Collective ideals focus on meaning and exploration.",
    Capricorn: "Your generation dreams of dissolving rigid structures. Collective ideals challenge traditional institutions.",
    Aquarius: "Your generation dreams of technological utopia and collective awakening. Collective ideals focus on unity.",
    Pisces: "Your generation dreams of spiritual transcendence and unity. Collective ideals focus on compassion and imagination.",
  },
  Pluto: {
    Aries: "Your generation transforms through radical individualism and new beginnings. Power comes through pioneering action.",
    Taurus: "Your generation transforms through redefining value and resources. Power comes through sustainable change.",
    Gemini: "Your generation transforms through information and communication revolution. Power comes through knowledge sharing.",
    Cancer: "Your generation transforms through family and emotional structures. Power comes through nurturing and protection.",
    Leo: "Your generation transforms through creative power and self-expression. Power comes through courageous individuality.",
    Virgo: "Your generation transforms through health and work revolution. Power comes through practical service and healing.",
    Libra: "Your generation transforms through relationships and social justice. Power comes through partnership and diplomacy.",
    Scorpio: "Your generation transforms through intense psychological depth. Power comes through confronting shadow and rebirth.",
    Sagittarius: "Your generation transforms through beliefs and global understanding. Power comes through truth and exploration.",
    Capricorn: "Your generation transforms through restructuring institutions. Power comes through disciplined change and authority.",
    Aquarius: "Your generation transforms through technology and social revolution. Power comes through collective innovation.",
    Pisces: "Your generation transforms through spiritual awakening and compassion. Power comes through transcendence and healing.",
  },
};

export const planetInHouse = {
  Sun: {
    1: "Your identity and self-expression are central to your life path. You project confidence and personal magnetism.",
    2: "Your sense of self is tied to your values and resources. Building financial security boosts your confidence.",
    3: "Your identity shines through communication and learning. You're known for your ideas and local connections.",
    4: "Your identity is rooted in home and family. Private life and emotional foundations define who you are.",
    5: "Your identity radiates through creativity and romance. You shine when expressing yourself and having fun.",
    6: "Your identity is expressed through work and service. Daily routines and health practices define your purpose.",
    7: "Your identity develops through partnerships. Relationships mirror who you are and who you're becoming.",
    8: "Your identity transforms through deep experiences. Shared resources and emotional intensity shape your path.",
    9: "Your identity expands through philosophy and travel. Higher learning and beliefs define your worldview.",
    10: "Your identity is defined by career and public reputation. You're driven to achieve and be recognized.",
    11: "Your identity connects to community and future visions. Friends and social causes shape who you are.",
    12: "Your identity unfolds in solitude and spiritual practice. Your inner world is rich and deeply private.",
  },
  Moon: {
    1: "Your emotions are visible and shape how others see you. You wear your heart on your sleeve.",
    2: "Emotional security comes through financial stability. Comfort and material possessions nurture your soul.",
    3: "You process emotions through talking and writing. Siblings and neighbors play important emotional roles.",
    4: "Home is your emotional sanctuary. Family bonds and domestic life deeply affect your well-being.",
    5: "You find emotional fulfillment through creativity and romance. Children and play bring you joy.",
    6: "Your emotions affect your health and daily work. Service to others fulfills your emotional needs.",
    7: "Emotional fulfillment comes through partnerships. You need close relationships to feel emotionally complete.",
    8: "Your emotions run deep and intense. Transformation and shared intimacy fulfill your emotional needs.",
    9: "You find emotional fulfillment through learning and travel. Philosophy and beliefs shape your feelings.",
    10: "Your emotions are tied to career and public life. Professional achievement provides emotional satisfaction.",
    11: "Friendships and community provide emotional sustenance. You feel nurtured within groups and social networks.",
    12: "Your emotional life is private and deeply spiritual. Solitude and reflection restore your inner peace.",
  },
  Mercury: {
    1: "You lead with your intellect and communicate naturally. First impressions show your quick, curious mind.",
    2: "Your mind focuses on values and finances. You think practically about resources and earning potential.",
    3: "Communication is your strength. You excel at learning, teaching, and connecting with your local community.",
    4: "Your thinking is influenced by family and upbringing. Home is where your mind is most active.",
    5: "Your mind is creative and playful. You communicate through art, drama, and entertaining expression.",
    6: "Your mind focuses on practical details and health. You think analytically about work and daily routines.",
    7: "Your thinking is shaped by partnerships. You communicate best in one-on-one conversations and negotiations.",
    8: "Your mind penetrates beneath surfaces. You think deeply about psychology, mystery, and shared resources.",
    9: "Your mind is philosophical and expansive. You love learning about cultures, religions, and big ideas.",
    10: "Your communication skills drive your career. You're known professionally for your intellect and ideas.",
    11: "Your mind connects with groups and future visions. You think innovatively and communicate within communities.",
    12: "Your mind works best in solitude. Your thinking is intuitive, private, and spiritually inclined.",
  },
  Venus: {
    1: "You radiate charm and attractiveness. Love and beauty are central to how you present yourself.",
    2: "You attract resources and value beautiful possessions. Financial comfort and sensory pleasures bring happiness.",
    3: "You attract through words and social connections. Love comes through communication and intellectual bonds.",
    4: "You find love and beauty in domestic life. Home is where your heart truly feels at peace.",
    5: "Romance, creativity, and fun are your love languages. You attract through playful, creative expression.",
    6: "You show love through service and daily devotion. Health and work routines bring you satisfaction.",
    7: "Partnership is central to your happiness. You thrive in committed, harmonious relationships.",
    8: "Love is intense and transformative for you. Deep emotional and physical bonding defines your relationships.",
    9: "You find love through adventure and learning. Cross-cultural connections and philosophical bonds attract you.",
    10: "Love and career are intertwined. You're attracted to status and find beauty in professional achievement.",
    11: "Friendships are a source of love and happiness. You value community connections and shared ideals.",
    12: "Love is private, spiritual, and compassionate. You find beauty in solitude and selfless giving.",
  },
  Mars: {
    1: "You're assertive, energetic, and action-oriented. Physical vitality and personal drive define your approach.",
    2: "Your drive focuses on earning and building security. You're aggressive about protecting your resources.",
    3: "Your energy goes into communication and learning. You're mentally competitive and verbally assertive.",
    4: "Your drive focuses on home and family matters. You're protective of your private life and roots.",
    5: "Your energy goes into creativity, romance, and fun. You're passionate in love and competitive in play.",
    6: "Your drive focuses on work and health. You're energetic about routines and serving others efficiently.",
    7: "Your energy is directed toward partnerships. You're assertive in relationships and may attract strong partners.",
    8: "Your drive is intense and transformative. You're powerful in managing shared resources and emotional depth.",
    9: "Your energy goes into exploration and beliefs. You're passionate about philosophy, travel, and higher learning.",
    10: "Your drive focuses on career and public achievement. You're ambitious and assertive in professional life.",
    11: "Your energy goes into group activities and causes. You're a dynamic force within communities and organizations.",
    12: "Your drive operates behind the scenes. You take action privately and channel energy into spiritual pursuits.",
  },
  Jupiter: {
    1: "Luck and expansion come through personal growth. You have a naturally optimistic and generous presence.",
    2: "Luck and expansion come through finances. You have potential for material abundance and resource growth.",
    3: "Luck comes through communication and learning. Short travels and intellectual pursuits bring opportunities.",
    4: "Luck comes through family and real estate. Home life is a source of abundance and emotional growth.",
    5: "Luck comes through creativity and romance. Creative projects and children bring joy and expansion.",
    6: "Luck comes through work and health practices. Service to others and routines lead to growth.",
    7: "Luck comes through partnerships. Marriage and business collaborations bring abundance and opportunity.",
    8: "Luck comes through shared resources and transformation. Inheritance, investments, and deep bonds bring growth.",
    9: "Luck comes through travel, education, and philosophy. This is Jupiter's natural house of expansion.",
    10: "Luck comes through career and public recognition. Professional life brings abundance and social standing.",
    11: "Luck comes through friends and community. Social networks and group involvement create opportunities.",
    12: "Luck comes through spirituality and solitude. Behind-the-scenes efforts and charitable work bring blessings.",
  },
  Saturn: {
    1: "Life lessons come through self-identity. You develop discipline and responsibility as a core part of who you are.",
    2: "Life lessons come through finances and values. You learn discipline through managing resources carefully.",
    3: "Life lessons come through communication. You develop disciplined thinking and careful speech over time.",
    4: "Life lessons come through family and home. You build emotional foundations through responsibility and structure.",
    5: "Life lessons come through creativity and romance. Self-expression requires discipline and mature effort.",
    6: "Life lessons come through work and health. Daily routines and service demand discipline and commitment.",
    7: "Life lessons come through partnerships. Relationships require commitment, patience, and mature responsibility.",
    8: "Life lessons come through shared resources and transformation. Emotional depth requires boundary and discipline.",
    9: "Life lessons come through beliefs and education. Philosophy and travel demand practical grounding.",
    10: "Life lessons come through career. Professional mastery requires patience, hard work, and perseverance.",
    11: "Life lessons come through community. Building lasting friendships and group contributions takes time.",
    12: "Life lessons come through solitude and spirituality. Inner work and letting go require discipline.",
  },
  Uranus: {
    1: "Unexpected changes shape your identity. You're seen as unique, rebellious, or ahead of your time.",
    2: "Unexpected changes affect your finances. You have unconventional approaches to earning and values.",
    3: "Unexpected changes come through communication. Your thinking is innovative and your ideas are original.",
    4: "Unexpected changes affect home and family. Your domestic life is unconventional or frequently shifting.",
    5: "Unexpected changes come through creativity and romance. Your creative expression is original and surprising.",
    6: "Unexpected changes affect work and health. You need variety and innovation in daily routines.",
    7: "Unexpected changes come through relationships. Your partnerships are unconventional or suddenly transformative.",
    8: "Unexpected changes come through shared resources. Transformation happens suddenly and profoundly.",
    9: "Unexpected changes come through beliefs and travel. Your worldview is progressive and ever-evolving.",
    10: "Unexpected changes affect your career. Your professional path is unconventional and full of surprises.",
    11: "Unexpected changes come through community. You're drawn to progressive groups and humanitarian causes.",
    12: "Unexpected changes come from the unconscious. Hidden awakenings and spiritual breakthroughs transform you.",
  },
  Neptune: {
    1: "Spiritual and creative energy shapes your identity. Others may see you as dreamy, artistic, or elusive.",
    2: "Spiritual energy affects finances and values. You may idealize or be confused about material resources.",
    3: "Spiritual energy flows through communication. Your thinking is intuitive, poetic, and imaginative.",
    4: "Spiritual energy infuses your home life. Family connections have a mystical or idealised quality.",
    5: "Spiritual energy enhances creativity and romance. Your artistic expression is inspired and transcendent.",
    6: "Spiritual energy affects work and health. Healing, service, and holistic practices are important.",
    7: "Spiritual energy flows through partnerships. You idealize relationships and seek soulmate connections.",
    8: "Spiritual energy deepens transformation. Psychic sensitivity and mystical experiences shape your growth.",
    9: "Spiritual energy expands through philosophy and travel. Your beliefs are idealistic and universally compassionate.",
    10: "Spiritual energy shapes your career. You're drawn to creative, healing, or service-oriented professions.",
    11: "Spiritual energy connects you to groups. You're drawn to humanitarian ideals and visionary communities.",
    12: "Spiritual energy is strongest here. You have deep intuition, rich inner life, and psychic sensitivity.",
  },
  Pluto: {
    1: "Transformation defines your identity. You project intensity and undergo powerful personal reinventions.",
    2: "Transformation affects your finances and values. You experience deep shifts in what you consider valuable.",
    3: "Transformation comes through communication. Your words carry power and you uncover hidden truths.",
    4: "Transformation shapes your home and family. Deep psychological patterns from childhood drive your evolution.",
    5: "Transformation comes through creativity and romance. Love and self-expression involve intense, deep experiences.",
    6: "Transformation affects work and health. You undergo powerful changes in daily habits and service.",
    7: "Transformation comes through relationships. Partnerships are intense and bring profound personal evolution.",
    8: "Transformation is your deepest theme. Rebirth, shared resources, and emotional power define your path.",
    9: "Transformation comes through beliefs and worldview. Your philosophy of life undergoes profound evolution.",
    10: "Transformation shapes your career and public role. You wield power and influence in professional life.",
    11: "Transformation comes through community and causes. You're a powerful force for social change.",
    12: "Transformation happens in the unconscious. Deep spiritual and psychological healing defines your journey.",
  },
};

export const houseDescriptions = {
  1: "Self, identity, appearance, and how you present to the world",
  2: "Money, possessions, values, and self-worth",
  3: "Communication, learning, siblings, and short journeys",
  4: "Home, family, roots, and emotional foundations",
  5: "Creativity, romance, children, fun, and self-expression",
  6: "Work, health, daily routines, and service",
  7: "Partnerships, marriage, contracts, and open relationships",
  8: "Transformation, shared resources, intimacy, and rebirth",
  9: "Philosophy, higher education, travel, and beliefs",
  10: "Career, public reputation, authority, and life goals",
  11: "Friends, community, social causes, and future visions",
  12: "Spirituality, solitude, the unconscious, and hidden strengths",
};
